"""Register map for the Phnix KHX R290 heat pump (WarmLink product 644).

GENERATED by tools/gen_integration.py - do not edit by hand.
Source of truth: out/modbus_map_644.csv (101 mapped codes, 53 verified
against the live unit with 0 mismatches).
"""

DOMAIN = "phnix_khx"
CONF_NAME = "name"
CONF_HOST = "host"
CONF_PORT = "port"
CONF_SLAVE = "slave"
CONF_SCAN_INTERVAL = "scan_interval"
DEFAULT_NAME = "Phnix KHX"
DEFAULT_PORT = 502
DEFAULT_SLAVE = 1
DEFAULT_SCAN_INTERVAL = 10

# (key, name, address, scale, precision, device_class, unit, signed)
SENSORS: list[dict] = [
    {"key": "ac_input_voltage", "name": "AC Input Voltage", "address": 2062, "scale": 1, "precision": 0, "device_class": 'voltage', "unit": 'V', "signed": False},
    {"key": "ac_input_current", "name": "AC Input Current", "address": 2057, "scale": 0.1, "precision": 1, "device_class": 'current', "unit": 'A', "signed": True},
    {"key": "dc_bus_voltage", "name": "DC Bus Voltage", "address": 2043, "scale": 1, "precision": 0, "device_class": 'voltage', "unit": 'V', "signed": False},
    {"key": "water_in_temperature", "name": "Water IN Temperature", "address": 2045, "scale": 0.1, "precision": 1, "device_class": 'temperature', "unit": '°C', "signed": True},
    {"key": "water_out_temperature", "name": "Water OUT Temperature", "address": 2046, "scale": 0.1, "precision": 1, "device_class": 'temperature', "unit": '°C', "signed": True},
    {"key": "dhw_temperature", "name": "DHW Temperature", "address": 2047, "scale": 0.1, "precision": 1, "device_class": 'temperature', "unit": '°C', "signed": True},
    {"key": "ambient_temperature", "name": "Ambient Temperature", "address": 2048, "scale": 0.1, "precision": 1, "device_class": 'temperature', "unit": '°C', "signed": True},
    {"key": "coil_temperature", "name": "Coil Temperature", "address": 2049, "scale": 0.1, "precision": 1, "device_class": 'temperature', "unit": '°C', "signed": True},
    {"key": "exhaust_temperature", "name": "Exhaust Temperature", "address": 2053, "scale": 0.1, "precision": 1, "device_class": 'temperature', "unit": '°C', "signed": True},
    {"key": "compressor_speed", "name": "Compressor Speed", "address": 2072, "scale": 1, "precision": 0, "device_class": None, "unit": 'Hz', "signed": False},
    {"key": "fan_speed", "name": "Fan Speed", "address": 2074, "scale": 1, "precision": 0, "device_class": None, "unit": 'RPM', "signed": False},
    {"key": "fan_2_speed", "name": "Fan 2 Speed", "address": 2075, "scale": 1, "precision": 0, "device_class": None, "unit": 'RPM', "signed": False},
    {"key": "low_pressure", "name": "Low Pressure", "address": 2069, "scale": 0.1, "precision": 1, "device_class": None, "unit": 'Bar', "signed": True},
    {"key": "target_after_limit", "name": "Target Temp After Limit", "address": 2013, "scale": 0.1, "precision": 1, "device_class": 'temperature', "unit": '°C', "signed": True},
    {"key": "target_after_compensation", "name": "Target Temp After Compensation", "address": 2014, "scale": 0.1, "precision": 1, "device_class": 'temperature', "unit": '°C', "signed": True},
    {"key": "output_bits", "name": "Output Bits", "address": 2019, "scale": 1, "precision": 0, "device_class": None, "unit": None, "signed": False},
    {"key": "switch_bits", "name": "Switch Bits", "address": 2034, "scale": 1, "precision": 0, "device_class": None, "unit": None, "signed": False},
    {"key": "power_state", "name": "Power State", "address": 2011, "scale": 1, "precision": 0, "device_class": None, "unit": None, "signed": False},
    {"key": "run_mode_state", "name": "Run Mode State", "address": 2012, "scale": 1, "precision": 0, "device_class": None, "unit": None, "signed": False},
]

# (key, name, address, scale, minimum, maximum, step, unit)
NUMBERS: list[dict] = [
    {"key": "dhw_target_temperature", "name": "DHW Target Temperature", "address": 1157, "scale": 0.1, "min": 15, "max": 85, "step": 0.1, "unit": '°C'},
    {"key": "heating_target_temperature", "name": "Heating Target Temperature", "address": 1158, "scale": 0.1, "min": 15, "max": 99, "step": 0.1, "unit": '°C'},
    {"key": "cooling_target_temperature", "name": "Cooling Target Temperature", "address": 1159, "scale": 0.1, "min": 5, "max": 80, "step": 0.1, "unit": '°C'},
    {"key": "power_on_diff_heating", "name": "Power-on Diff Heating", "address": 1160, "scale": 0.1, "min": 0, "max": 10, "step": 0.1, "unit": '°C'},
    {"key": "standby_diff_heating", "name": "Standby Diff Heating", "address": 1161, "scale": 0.1, "min": 0, "max": 10, "step": 0.1, "unit": '°C'},
    {"key": "power_on_diff_cooling", "name": "Power-on Diff Cooling", "address": 1174, "scale": 0.1, "min": 0, "max": 10, "step": 0.1, "unit": '°C'},
    {"key": "standby_diff_cooling", "name": "Standby Diff Cooling", "address": 1175, "scale": 0.1, "min": 0, "max": 10, "step": 0.1, "unit": '°C'},
    {"key": "power_on_diff_dhw", "name": "Power-on Diff DHW", "address": 1195, "scale": 0.1, "min": 0, "max": 10, "step": 0.1, "unit": '°C'},
    {"key": "standby_diff_dhw", "name": "Standby Diff DHW", "address": 1196, "scale": 0.1, "min": 0, "max": 10, "step": 0.1, "unit": '°C'},
    {"key": "defrost_interval_time", "name": "Defrost Interval Time", "address": 1107, "scale": 1.0, "min": 10, "max": 90, "step": 1, "unit": 'min'},
    {"key": "max_defrosting_time", "name": "Max Defrosting Time", "address": 1124, "scale": 1.0, "min": 0, "max": 20, "step": 1, "unit": 'min'},
    {"key": "force_switch_mode_time", "name": "Force Switch Mode Time", "address": 1045, "scale": 1.0, "min": 1, "max": 300, "step": 1, "unit": 'min'},
    {"key": "max_outlet_water_temperature", "name": "Max Outlet Water Temperature", "address": 1238, "scale": 0.1, "min": 40, "max": 95, "step": 0.1, "unit": '°C'},
]

# (key, name, address, on, off, note)
SWITCHES: list[dict] = [
    {"key": "power", "name": "Power", "address": 1011, "on": 1, "off": 0, "note": '1011 power command'},
    {"key": "silent_mode", "name": "Silent Mode", "address": 1016, "on": 2, "off": 0, "note": '1016 silent: on=2 off=0'},
    {"key": "manual_pump_control", "name": "Manual Pump Control", "address": 1202, "on": 1, "off": 0, "note": 'P06 Main Circulation Pump Manual Control'},
]

# (key, name, address, options, values, note)
SELECTS: list[dict] = [
    {"key": "operating_mode", "name": "Operating Mode", "address": 1012, "options": ['Hot water', 'Heating', 'Cooling', 'Hot water + heating', 'Hot water + cooling'], "values": [0, 1, 2, 3, 4], "note": '1012 mode command'},
    {"key": "circulation_pump_mode", "name": "Circulation Pump Mode", "address": 1197, "options": ['Always On', 'Saving', 'Interval'], "values": [0, 1, 2], "note": 'P01 Main Circulation Pump Operation Mode'},
    {"key": "dhw_pump_mode", "name": "DHW Pump Mode", "address": 1201, "options": ['Always On', 'Saving', 'Interval'], "values": [0, 1, 2], "note": 'P05 DHW Pump Operation Mode'},
    {"key": "electric_heater_location", "name": "Electric Heater Location", "address": 1173, "options": ['Not Used', 'Waterline', 'Water Tank'], "values": [0, 1, 2], "note": 'R35 Location of Electric Heater'},
    {"key": "dhw_temp_sourcing", "name": "DHW Temp Sourcing", "address": 1129, "options": ['DHW Tank Sensor', 'External from Modbus'], "values": [0, 1], "note": 'H37 DHW Temp. Sourcing'},
]
